package FRSManager;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Handles event handling, displays the various traveling options and other
 * GUI operations of Screen 2
 * @author Allama
 */
public class Screen2 extends javax.swing.JFrame {

    /**
     * Creates new form Screen2
     */
    
    private FRSManager mgr;
    public Screen2(FRSManager mgr) {
        this.mgr= mgr;
        initComponents();
        initialize();
    }
   private Screen2()
    {
        initComponents();
    }
    /**
     * Function to initialize and set the software details, and other 
     * processes and utilities at the beginning
     */
    private void initialize()
    {
        
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                System.exit(0);
            }
            
        });
        jDialog1.setIconImage(new ImageIcon(getClass().getResource("/images/22.png")).getImage());
        jDialog1.setLocationRelativeTo(null);
        jDialog1.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("/images/3.png")).getImage());
        setSize(1360, 720);
        setPreferredSize(new Dimension(1360, 720));
        setTitle("Travel World");
        setLocationRelativeTo(null);
        setResizable(true);
        pack();
        setVisible(true);
        Font font = jLabel12.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        jLabel12.setFont(font.deriveFont(attributes));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel124 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jDialog1.setTitle("Error!");
        jDialog1.setSize(new java.awt.Dimension(430, 190));
        jDialog1.setType(java.awt.Window.Type.POPUP);
        jDialog1.getContentPane().setLayout(null);

        jPanel12.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/23.png"))); // NOI18N
        jLabel13.setText(" Choose your travel option:  This is a mandatory field; ");
        jPanel12.add(jLabel13);
        jLabel13.setBounds(10, 30, 500, 36);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("please review and try again.");
        jPanel12.add(jLabel21);
        jLabel21.setBounds(50, 60, 180, 36);

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton3);
        jButton3.setBounds(320, 110, 80, 30);

        jDialog1.getContentPane().add(jPanel12);
        jPanel12.setBounds(0, 0, 410, 150);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 166, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 60, 120, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 60, 120, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departing");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(630, 60, 120, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Passengers");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(920, 60, 120, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("departureCity");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 110, 120, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Singapore");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 110, 120, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("departureTime");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(630, 110, 180, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("noOfPassengers");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(920, 110, 120, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/15.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 70, 40, 40);

        jSeparator1.setBackground(new java.awt.Color(153, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(540, 60, 2, 90);

        jSeparator2.setBackground(new java.awt.Color(153, 0, 153));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(820, 60, 2, 90);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16.png"))); // NOI18N
        jLabel11.setText(" Choose your outbound trip");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 0, 270, 40);

        jLabel109.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel109.setText("jLabel109");
        jPanel2.add(jLabel109);
        jLabel109.setBounds(280, 0, 180, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 170, 1210, 40);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1250, 181));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1250, 1181));
        jPanel3.setLayout(null);

        jRadioButton1.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setAutoscrolls(true);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(1140, 70, 21, 40);

        jRadioButton2.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(1140, 270, 20, 40);

        jRadioButton3.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setToolTipText("");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton3);
        jRadioButton3.setBounds(1140, 470, 21, 40);

        jRadioButton4.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setToolTipText("");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton4);
        jRadioButton4.setBounds(1140, 670, 21, 40);

        jRadioButton5.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setToolTipText("");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton5);
        jRadioButton5.setBounds(1140, 870, 20, 40);

        jRadioButton6.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setToolTipText("");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton6);
        jRadioButton6.setBounds(1140, 1070, 21, 40);

        jRadioButton7.setBackground(new java.awt.Color(153, 0, 153));
        buttonGroup1.add(jRadioButton7);
        jPanel3.add(jRadioButton7);
        jRadioButton7.setBounds(1140, 1270, 20, 40);
        jRadioButton7.getAccessibleContext().setAccessibleDescription("");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel4.setLayout(null);

        j1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j1.setText("FromCity");
        j1.setName("1"); // NOI18N
        jPanel4.add(j1);
        j1.setBounds(10, 20, 140, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel4.add(jLabel20);
        jLabel20.setBounds(170, 20, 40, 40);

        j2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j2.setText("Chennai");
        jPanel4.add(j2);
        j2.setBounds(230, 20, 210, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("06:00");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(580, 20, 90, 40);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("08:50");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(710, 20, 90, 40);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("2 hours 50 minutes");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(830, 20, 140, 40);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("SG109");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(990, 20, 90, 40);

        jLabel26.setBackground(new java.awt.Color(153, 153, 153));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        jLabel26.setOpaque(true);
        jPanel4.add(jLabel26);
        jLabel26.setBounds(10, 70, 1190, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Chennai");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(10, 130, 140, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(170, 130, 40, 40);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Singapore(SIN)");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(230, 130, 210, 40);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("11:15");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(580, 130, 90, 40);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("17:55");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(710, 130, 90, 40);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("6 hours 40 minutes");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(830, 130, 140, 40);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("SQ529");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(990, 130, 90, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(10, 0, 1210, 180);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel5.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("jLabel34");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(580, 20, 90, 40);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("FromCity");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(10, 20, 140, 40);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jLabel36.setText("jLabel36");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(170, 20, 40, 40);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("ConnCity");
        jPanel5.add(jLabel37);
        jLabel37.setBounds(230, 20, 210, 40);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("jLabel38");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(710, 20, 90, 40);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("jLabel39");
        jPanel5.add(jLabel39);
        jLabel39.setBounds(830, 20, 140, 40);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("jLabel40");
        jPanel5.add(jLabel40);
        jLabel40.setBounds(990, 20, 90, 40);

        jLabel41.setBackground(new java.awt.Color(153, 153, 153));
        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20.png"))); // NOI18N
        jLabel41.setText("jLabel41");
        jLabel41.setOpaque(true);
        jPanel5.add(jLabel41);
        jLabel41.setBounds(10, 70, 1190, 40);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("ConnCity");
        jPanel5.add(jLabel42);
        jLabel42.setBounds(10, 130, 140, 40);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jLabel43.setText("jLabel43");
        jPanel5.add(jLabel43);
        jLabel43.setBounds(170, 130, 40, 40);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText("Singapore(SIN)");
        jPanel5.add(jLabel44);
        jLabel44.setBounds(230, 130, 210, 40);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("jLabel45");
        jPanel5.add(jLabel45);
        jLabel45.setBounds(580, 130, 90, 40);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("jLabel46");
        jPanel5.add(jLabel46);
        jLabel46.setBounds(710, 130, 90, 40);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("jLabel47");
        jPanel5.add(jLabel47);
        jLabel47.setBounds(830, 130, 140, 40);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("jLabel48");
        jPanel5.add(jLabel48);
        jLabel48.setBounds(990, 130, 90, 40);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(10, 200, 1210, 180);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel6.setLayout(null);

        jLabel50.setBackground(new java.awt.Color(153, 153, 153));
        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20.png"))); // NOI18N
        jLabel50.setText("jLabel50");
        jLabel50.setOpaque(true);
        jPanel6.add(jLabel50);
        jLabel50.setBounds(10, 70, 1190, 40);

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel67.setText("FromCity");
        jPanel6.add(jLabel67);
        jLabel67.setBounds(10, 20, 140, 40);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel6.add(jLabel68);
        jLabel68.setBounds(170, 20, 40, 40);

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setText("ConnCity");
        jPanel6.add(jLabel69);
        jLabel69.setBounds(230, 20, 210, 40);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("jLabel70");
        jPanel6.add(jLabel70);
        jLabel70.setBounds(580, 20, 90, 40);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("jLabel71");
        jPanel6.add(jLabel71);
        jLabel71.setBounds(710, 20, 90, 40);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("jLabel72");
        jPanel6.add(jLabel72);
        jLabel72.setBounds(830, 20, 140, 40);

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel73.setText("jLabel73");
        jPanel6.add(jLabel73);
        jLabel73.setBounds(990, 20, 90, 40);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel74.setText("ConnCity");
        jPanel6.add(jLabel74);
        jLabel74.setBounds(10, 130, 140, 40);

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel6.add(jLabel75);
        jLabel75.setBounds(170, 130, 40, 40);

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel76.setText("Singapore(SIN)");
        jPanel6.add(jLabel76);
        jLabel76.setBounds(230, 130, 210, 40);

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel77.setText("jLabel77");
        jPanel6.add(jLabel77);
        jLabel77.setBounds(580, 130, 90, 40);

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel78.setText("jLabel78");
        jPanel6.add(jLabel78);
        jLabel78.setBounds(710, 130, 90, 40);

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel79.setText("jLabel79");
        jPanel6.add(jLabel79);
        jLabel79.setBounds(830, 130, 140, 40);

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel80.setText("jLabel80");
        jPanel6.add(jLabel80);
        jLabel80.setBounds(990, 130, 90, 40);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(10, 600, 1210, 180);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel7.setLayout(null);

        jLabel52.setBackground(new java.awt.Color(153, 153, 153));
        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20.png"))); // NOI18N
        jLabel52.setText("jLabel52");
        jLabel52.setOpaque(true);
        jPanel7.add(jLabel52);
        jLabel52.setBounds(10, 70, 1190, 40);

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel95.setText("FromCity");
        jPanel7.add(jLabel95);
        jLabel95.setBounds(10, 20, 140, 40);

        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel7.add(jLabel96);
        jLabel96.setBounds(170, 20, 40, 40);

        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel97.setText("ConnCity");
        jPanel7.add(jLabel97);
        jLabel97.setBounds(230, 20, 210, 40);

        jLabel98.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel98.setText("jLabel98");
        jPanel7.add(jLabel98);
        jLabel98.setBounds(580, 20, 90, 40);

        jLabel99.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel99.setText("jLabel99");
        jPanel7.add(jLabel99);
        jLabel99.setBounds(710, 20, 90, 40);

        jLabel100.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel100.setText("jLabel100");
        jPanel7.add(jLabel100);
        jLabel100.setBounds(830, 20, 140, 40);

        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel101.setText("jLabel101");
        jPanel7.add(jLabel101);
        jLabel101.setBounds(990, 20, 90, 40);

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel102.setText("ConnCity");
        jPanel7.add(jLabel102);
        jLabel102.setBounds(10, 130, 140, 40);

        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel7.add(jLabel103);
        jLabel103.setBounds(170, 130, 40, 40);

        jLabel104.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel104.setText("Singapore(SIN)");
        jPanel7.add(jLabel104);
        jLabel104.setBounds(230, 130, 210, 40);

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel105.setText("jLabel105");
        jPanel7.add(jLabel105);
        jLabel105.setBounds(580, 130, 90, 40);

        jLabel106.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel106.setText("jLabel106");
        jPanel7.add(jLabel106);
        jLabel106.setBounds(710, 130, 90, 40);

        jLabel107.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel107.setText("jLabel107");
        jPanel7.add(jLabel107);
        jLabel107.setBounds(830, 130, 140, 40);

        jLabel108.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel108.setText("jLabel108");
        jPanel7.add(jLabel108);
        jLabel108.setBounds(990, 130, 90, 40);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(10, 1000, 1210, 180);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel8.setLayout(null);

        jLabel51.setBackground(new java.awt.Color(153, 153, 153));
        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20.png"))); // NOI18N
        jLabel51.setText("jLabel51");
        jLabel51.setOpaque(true);
        jPanel8.add(jLabel51);
        jLabel51.setBounds(10, 70, 1190, 40);

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel81.setText("FromCity");
        jPanel8.add(jLabel81);
        jLabel81.setBounds(10, 20, 140, 40);

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel8.add(jLabel82);
        jLabel82.setBounds(170, 20, 40, 40);

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel83.setText("ConnCity");
        jPanel8.add(jLabel83);
        jLabel83.setBounds(230, 20, 210, 40);

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setText("jLabel84");
        jPanel8.add(jLabel84);
        jLabel84.setBounds(580, 20, 90, 40);

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel85.setText("jLabel85");
        jPanel8.add(jLabel85);
        jLabel85.setBounds(710, 20, 90, 40);

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel86.setText("jLabel86");
        jPanel8.add(jLabel86);
        jLabel86.setBounds(830, 20, 140, 40);

        jLabel87.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel87.setText("jLabel87");
        jPanel8.add(jLabel87);
        jLabel87.setBounds(990, 20, 90, 40);

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel88.setText("ConnCity");
        jPanel8.add(jLabel88);
        jLabel88.setBounds(10, 130, 140, 40);

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel8.add(jLabel89);
        jLabel89.setBounds(170, 130, 40, 40);

        jLabel90.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel90.setText("Singapore(SIN)");
        jPanel8.add(jLabel90);
        jLabel90.setBounds(230, 130, 210, 40);

        jLabel91.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel91.setText("jLabel91");
        jPanel8.add(jLabel91);
        jLabel91.setBounds(580, 130, 90, 40);

        jLabel92.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel92.setText("jLabel92");
        jPanel8.add(jLabel92);
        jLabel92.setBounds(710, 130, 90, 40);

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel93.setText("jLabel93");
        jPanel8.add(jLabel93);
        jLabel93.setBounds(830, 130, 140, 40);

        jLabel94.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel94.setText("jLabel94");
        jPanel8.add(jLabel94);
        jLabel94.setBounds(990, 130, 90, 40);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(10, 800, 1210, 180);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel9.setLayout(null);

        jLabel49.setBackground(new java.awt.Color(153, 153, 153));
        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20.png"))); // NOI18N
        jLabel49.setText("jLabel49");
        jLabel49.setOpaque(true);
        jPanel9.add(jLabel49);
        jLabel49.setBounds(10, 70, 1190, 40);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("FromCity");
        jPanel9.add(jLabel53);
        jLabel53.setBounds(10, 20, 140, 40);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel9.add(jLabel54);
        jLabel54.setBounds(170, 20, 40, 40);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("ConnCity");
        jPanel9.add(jLabel55);
        jLabel55.setBounds(230, 20, 210, 40);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("jLabel56");
        jPanel9.add(jLabel56);
        jLabel56.setBounds(580, 20, 90, 40);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setText("jLabel57");
        jPanel9.add(jLabel57);
        jLabel57.setBounds(710, 20, 90, 40);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setText("jLabel58");
        jPanel9.add(jLabel58);
        jLabel58.setBounds(830, 20, 140, 40);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("jLabel59");
        jPanel9.add(jLabel59);
        jLabel59.setBounds(990, 20, 90, 40);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setText("ConnCity");
        jPanel9.add(jLabel60);
        jLabel60.setBounds(10, 130, 140, 40);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jPanel9.add(jLabel61);
        jLabel61.setBounds(170, 130, 40, 40);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setText("Singapore(SIN)");
        jPanel9.add(jLabel62);
        jLabel62.setBounds(230, 130, 210, 40);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel63.setText("jLabel63");
        jPanel9.add(jLabel63);
        jLabel63.setBounds(580, 130, 90, 40);

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel64.setText("jLabel64");
        jPanel9.add(jLabel64);
        jLabel64.setBounds(710, 130, 90, 40);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setText("jLabel65");
        jPanel9.add(jLabel65);
        jLabel65.setBounds(830, 130, 140, 40);

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel66.setText("jLabel66");
        jPanel9.add(jLabel66);
        jLabel66.setBounds(990, 130, 90, 40);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(10, 400, 1210, 180);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel11.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel11.add(jLabel14);
        jLabel14.setBounds(10, 20, 140, 40);

        jLabel110.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel110.setText("jLabel110");
        jPanel11.add(jLabel110);
        jLabel110.setBounds(220, 20, 210, 40);

        jLabel111.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel111.setText("jLabel111");
        jPanel11.add(jLabel111);
        jLabel111.setBounds(10, 130, 140, 40);

        jLabel112.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel112.setText("Singapore");
        jPanel11.add(jLabel112);
        jLabel112.setBounds(220, 130, 210, 40);

        jLabel113.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel113.setText("jLabel113");
        jPanel11.add(jLabel113);
        jLabel113.setBounds(570, 20, 90, 40);

        jLabel114.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel114.setText("jLabel114");
        jPanel11.add(jLabel114);
        jLabel114.setBounds(570, 130, 90, 40);

        jLabel115.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel115.setText("jLabel115");
        jPanel11.add(jLabel115);
        jLabel115.setBounds(710, 20, 90, 40);

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel116.setText("jLabel116");
        jPanel11.add(jLabel116);
        jLabel116.setBounds(710, 130, 90, 40);

        jLabel117.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel117.setText("jLabel117");
        jPanel11.add(jLabel117);
        jLabel117.setBounds(830, 20, 90, 40);

        jLabel118.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel118.setText("jLabel118");
        jPanel11.add(jLabel118);
        jLabel118.setBounds(830, 130, 90, 40);

        jLabel119.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel119.setText("jLabel119");
        jPanel11.add(jLabel119);
        jLabel119.setBounds(990, 20, 90, 40);

        jLabel120.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel120.setText("jLabel120");
        jPanel11.add(jLabel120);
        jLabel120.setBounds(990, 130, 90, 40);

        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jLabel121.setText("jLabel121");
        jPanel11.add(jLabel121);
        jLabel121.setBounds(170, 20, 40, 40);

        jLabel122.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        jLabel122.setText("jLabel122");
        jPanel11.add(jLabel122);
        jLabel122.setBounds(170, 130, 40, 40);

        jLabel123.setBackground(new java.awt.Color(153, 153, 153));
        jLabel123.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel123.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20.png"))); // NOI18N
        jLabel123.setText("jLabel123");
        jLabel123.setOpaque(true);
        jPanel11.add(jLabel123);
        jLabel123.setBounds(10, 70, 1190, 40);

        jPanel3.add(jPanel11);
        jPanel11.setBounds(10, 1200, 1210, 180);

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 260, 1250, 181);

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirm Selection");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1110, 630, 190, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cancel");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel12MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1040, 630, 60, 40);

        jButton2.setBackground(new java.awt.Color(153, 0, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Change Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1140, 90, 150, 40);

        jSeparator3.setForeground(new java.awt.Color(153, 0, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(1090, 60, 2, 90);

        jLabel124.setBackground(new java.awt.Color(0, 0, 0));
        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel124.setForeground(java.awt.Color.red);
        jLabel124.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/22.png"))); // NOI18N
        jLabel124.setText("Sorry no flights are available for 2nd November 2016. You can search again with another traveling date.");
        jLabel124.setOpaque(true);
        jPanel1.add(jLabel124);
        jLabel124.setBounds(50, 190, 1240, 60);

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        jPanel10.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Leg");
        jPanel10.add(jLabel19);
        jLabel19.setBounds(10, 0, 60, 30);
        jLabel19.getAccessibleContext().setAccessibleName("jLabel14");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Depart");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(580, 2, 80, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Arrive");
        jPanel10.add(jLabel16);
        jLabel16.setBounds(710, 2, 70, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Duration");
        jPanel10.add(jLabel17);
        jLabel17.setBounds(830, 2, 100, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Flight");
        jPanel10.add(jLabel18);
        jLabel18.setBounds(990, 2, 70, 30);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(60, 230, 1210, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1350, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Gives the user the option to modify his/her search by returning
     * to Screen 1
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mgr.displayMgr.ShowScreen1();
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Event Handling - Used to save the option the user has selected
     * and display a warning message in case no option has been selected
     * and then move to Screen3
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(buttonGroup1.getSelection()==null)
            jDialog1.setVisible(true);
        else
        {
            mgr.selectedCombo = mgr.myCombo[mgr.displayMgr.index];
            //System.out.println("Index: "+ mgr.displayMgr.index);
            mgr.displayMgr.ShowScreen3();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Used to cancel the current booking process and return to Screen1
     * for a new booking
     * @param evt 
     */
    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
        // TODO add your handling code here:
        mgr.displayMgr.ShowScreen1();
    }//GEN-LAST:event_jLabel12MouseReleased
    /**
     * Stores the details in case option 1 has been selected
     * @param evt 
     */
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        mgr.displayMgr.connCity = j2.getText();
        mgr.displayMgr.flight1 = jLabel25.getText();
        mgr.displayMgr.flight2 = jLabel33.getText();
        mgr.displayMgr.depTime1 = jLabel22.getText();
        mgr.displayMgr.depTime2 = jLabel30.getText();
        mgr.displayMgr.arrTime1 = jLabel23.getText();
        mgr.displayMgr.arrTime2 = jLabel31.getText();
        mgr.displayMgr.dur1 = jLabel24.getText();
        mgr.displayMgr.dur2 = jLabel32.getText();
        mgr.displayMgr.index = 0;
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    /**
     * Stores the details in case option 2 has been selected
     * @param evt 
     */
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        mgr.displayMgr.connCity = jLabel37.getText();
        mgr.displayMgr.flight1 = jLabel40.getText();
        mgr.displayMgr.flight2 = jLabel48.getText();
        mgr.displayMgr.depTime1 = jLabel34.getText();
        mgr.displayMgr.depTime2 = jLabel45.getText();
        mgr.displayMgr.arrTime1 = jLabel38.getText();
        mgr.displayMgr.arrTime2 = jLabel46.getText();
        mgr.displayMgr.dur1 = jLabel39.getText();
        mgr.displayMgr.dur2 = jLabel47.getText();
        mgr.displayMgr.index = 1;
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    /**
     * Stores the details in case option 3 has been selected
     * @param evt 
     */
    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        mgr.displayMgr.connCity = jLabel55.getText();
        mgr.displayMgr.flight1 = jLabel59.getText();
        mgr.displayMgr.flight2 = jLabel66.getText();
        mgr.displayMgr.depTime1 = jLabel56.getText();
        mgr.displayMgr.depTime2 = jLabel63.getText();
        mgr.displayMgr.arrTime1 = jLabel57.getText();
        mgr.displayMgr.arrTime2 = jLabel64.getText();
        mgr.displayMgr.dur1 = jLabel58.getText();
        mgr.displayMgr.dur2 = jLabel65.getText();
        mgr.displayMgr.index = 2;
    }//GEN-LAST:event_jRadioButton3ActionPerformed
    /**
     * Stores the details in case option 4 has been selected
     * @param evt 
     */
    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        mgr.displayMgr.connCity = jLabel69.getText();
        mgr.displayMgr.flight1 = jLabel73.getText();
        mgr.displayMgr.flight2 = jLabel80.getText();
        mgr.displayMgr.depTime1 = jLabel70.getText();
        mgr.displayMgr.depTime2 = jLabel77.getText();
        mgr.displayMgr.arrTime1 = jLabel71.getText();
        mgr.displayMgr.arrTime2 = jLabel78.getText();
        mgr.displayMgr.dur1 = jLabel72.getText();
        mgr.displayMgr.dur2 = jLabel79.getText();
        mgr.displayMgr.index = 3;
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    /**
     * Stores the details in case option 5 has been selected
     * @param evt 
     */
    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        mgr.displayMgr.connCity = jLabel83.getText();
        mgr.displayMgr.flight1 = jLabel87.getText();
        mgr.displayMgr.flight2 = jLabel94.getText();
        mgr.displayMgr.depTime1 = jLabel84.getText();
        mgr.displayMgr.depTime2 = jLabel91.getText();
        mgr.displayMgr.arrTime1 = jLabel85.getText();
        mgr.displayMgr.arrTime2 = jLabel92.getText();
        mgr.displayMgr.dur1 = jLabel86.getText();
        mgr.displayMgr.dur2 = jLabel93.getText();
        mgr.displayMgr.index = 4;
    }//GEN-LAST:event_jRadioButton5ActionPerformed
    /**
     * Stores the details in case option 6 has been selected
     * @param evt 
     */
    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        mgr.displayMgr.connCity = jLabel97.getText();
        mgr.displayMgr.flight1 = jLabel101.getText();
        mgr.displayMgr.flight2 = jLabel108.getText();
        mgr.displayMgr.depTime1 = jLabel98.getText();
        mgr.displayMgr.depTime2 = jLabel105.getText();
        mgr.displayMgr.arrTime1 = jLabel99.getText();
        mgr.displayMgr.arrTime2 = jLabel106.getText();
        mgr.displayMgr.dur1 = jLabel100.getText();
        mgr.displayMgr.dur2 = jLabel107.getText();
        mgr.displayMgr.index = 5;
    }//GEN-LAST:event_jRadioButton6ActionPerformed
    /**
     * Used to suspend the warning message
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JLabel j1;
    protected javax.swing.JLabel j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    protected javax.swing.JLabel jLabel100;
    protected javax.swing.JLabel jLabel101;
    protected javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    protected javax.swing.JLabel jLabel104;
    protected javax.swing.JLabel jLabel105;
    protected javax.swing.JLabel jLabel106;
    protected javax.swing.JLabel jLabel107;
    protected javax.swing.JLabel jLabel108;
    protected javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    protected javax.swing.JLabel jLabel110;
    protected javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    protected javax.swing.JLabel jLabel113;
    protected javax.swing.JLabel jLabel114;
    protected javax.swing.JLabel jLabel115;
    protected javax.swing.JLabel jLabel116;
    protected javax.swing.JLabel jLabel117;
    protected javax.swing.JLabel jLabel118;
    protected javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    protected javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    protected javax.swing.JLabel jLabel123;
    protected javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel13;
    protected javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    protected javax.swing.JLabel jLabel22;
    protected javax.swing.JLabel jLabel23;
    protected javax.swing.JLabel jLabel24;
    protected javax.swing.JLabel jLabel25;
    protected javax.swing.JLabel jLabel26;
    protected javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    protected javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel30;
    protected javax.swing.JLabel jLabel31;
    protected javax.swing.JLabel jLabel32;
    protected javax.swing.JLabel jLabel33;
    protected javax.swing.JLabel jLabel34;
    protected javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    protected javax.swing.JLabel jLabel37;
    protected javax.swing.JLabel jLabel38;
    protected javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel40;
    protected javax.swing.JLabel jLabel41;
    protected javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    protected javax.swing.JLabel jLabel44;
    protected javax.swing.JLabel jLabel45;
    protected javax.swing.JLabel jLabel46;
    protected javax.swing.JLabel jLabel47;
    protected javax.swing.JLabel jLabel48;
    protected javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    protected javax.swing.JLabel jLabel50;
    protected javax.swing.JLabel jLabel51;
    protected javax.swing.JLabel jLabel52;
    protected javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    protected javax.swing.JLabel jLabel55;
    protected javax.swing.JLabel jLabel56;
    protected javax.swing.JLabel jLabel57;
    protected javax.swing.JLabel jLabel58;
    protected javax.swing.JLabel jLabel59;
    protected javax.swing.JLabel jLabel6;
    protected javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    protected javax.swing.JLabel jLabel62;
    protected javax.swing.JLabel jLabel63;
    protected javax.swing.JLabel jLabel64;
    protected javax.swing.JLabel jLabel65;
    protected javax.swing.JLabel jLabel66;
    protected javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    protected javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    protected javax.swing.JLabel jLabel70;
    protected javax.swing.JLabel jLabel71;
    protected javax.swing.JLabel jLabel72;
    protected javax.swing.JLabel jLabel73;
    protected javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    protected javax.swing.JLabel jLabel76;
    protected javax.swing.JLabel jLabel77;
    protected javax.swing.JLabel jLabel78;
    protected javax.swing.JLabel jLabel79;
    protected javax.swing.JLabel jLabel8;
    protected javax.swing.JLabel jLabel80;
    protected javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    protected javax.swing.JLabel jLabel83;
    protected javax.swing.JLabel jLabel84;
    protected javax.swing.JLabel jLabel85;
    protected javax.swing.JLabel jLabel86;
    protected javax.swing.JLabel jLabel87;
    protected javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    protected javax.swing.JLabel jLabel9;
    protected javax.swing.JLabel jLabel90;
    protected javax.swing.JLabel jLabel91;
    protected javax.swing.JLabel jLabel92;
    protected javax.swing.JLabel jLabel93;
    protected javax.swing.JLabel jLabel94;
    protected javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    protected javax.swing.JLabel jLabel97;
    protected javax.swing.JLabel jLabel98;
    protected javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    protected javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

}

